### ISSUE TITLE
Enlarging aura changes player size for 1 frame and then never again

### ISSUE THREAD

**Issue by pncl9500** [sonic3XE/evades-region-editor#1]
https://github.com/sonic3XE/evades-region-editor/assets/80725620/63be7d21-6d94-4bb2-a190-f23275c8102e

as is seen in the attached video, the enlarging aura only affects the player for 1 frame.

**Comment by pncl9500** [comment]
A slight error is in the video - for the first test, the player is not enlarged at all, but this isn't a problem with the enlarging aura. I just used a video compressor that made it 30fps and the frame in which the player was enlarged was skipped, so don't worry about that.

**Comment by sonic3XE** [comment]
it should be fixed...
