### ISSUE TITLE
Cache up-to-date region files from EvadesClassic to evades-region-editor inside regions directory

### ISSUE THREAD

**Issue by sonic3XE** [sonic3XE/evades-region-editor#12]
This is a request for Junior Developers and Developers as I was going to make this issue because it would be nice to have up-to-date region files if the cache happens accordingly. [See problem in discord](https://discord.com/channels/283154072675287040/1032089336130310175/1250071481891950602)

The list of Evades.io Developer Team (@Spacebrook) as follows:
* Stovoy
* MiceLee (former)
* TheArctosJackal (junior dev)
* TTTruck (junior dev)
* Kaluub (junior dev)
* amasterclasher (junior dev)
* PotatoNuke (junior dev)

**Comment by Ino5559** [comment]
the select panelis making? i found button is saids select a  region but this disabled

**Comment by Ino5559** [comment]
![image](https://github.com/sonic3XE/evades-region-editor/assets/139974491/910e4cdf-d9e5-40ec-a2fe-2176317139c5)
um?

**Comment by sonic3XE** [comment]
@Ino5559, the japanese text is reverted: bbbbd463cd4c51b26ee4b94b93aca744fab0fbd4

**Comment by sonic3XE** [comment]
Looks like amasterclasher has made this google drive folder that keeps them up to date. I'll close this issue with the link :)
https://drive.google.com/drive/folders/1qzKh8cWHTqZC12WoJN6NpkdYw2tBRAia?usp=sharing
