### ISSUE TITLE
Crumbling enemy crashes editor

### ISSUE THREAD

**Issue by pncl9500** [sonic3XE/evades-region-editor#18]
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/85b9bff8-eb70-4a73-a4e5-a34db6f82621">

**Comment by sonic3XE** [comment]
Residue crash has been fixed. Unfortunately, there is no formula for enemies that return to original stats.

**Comment by sonic3XE** [comment]
made this formula: `x=(x+0.015)*pow(0.425,delta/1e3)`. I wonder what if this works properly.
