### ISSUE TITLE
Region Editor not working

### ISSUE THREAD

**Issue by RobertDaNoob** [sonic3XE/evades-region-editor#20]
hi sonic! if you're seeing this, just telling you that your editor isn't working atm and it just shows a picture of you in MM 120 (also does a glitch effect after a bit of a while). is there anything that has happened for this to cause? if so when will it be back? thanks!

**Comment by HalReturns** [comment]
the mm 120 picture is actually a video if u stay long enough it redirects u to the changelog page but with a twist

**Comment by sonic3XE** [comment]
You should read the region editor changelog which you can click [here](https://sonic3xe.github.io/).
